name: Build and Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Theos
      run: |
        export THEOS=/opt/theos
        git clone --recursive https://github.com/theos/theos.git $THEOS
        echo "THEOS=$THEOS" >> $GITHUB_ENV
    
    - name: Install iOS SDK
      run: |
        cd $THEOS/sdks
        wget -q https://github.com/theos/sdks/archive/master.zip
        unzip -q master.zip
        mv sdks-master/* .
        rm -rf sdks-master master.zip
    
    - name: Build tweak
      run: |
        export THEOS=/opt/theos
        make clean || true
        make package
    
    - name: Find build artifacts
      id: find_artifacts
      run: |
        DEB_FILE=$(find . -name "*.deb" -type f | head -n 1)
        DYLIB_FILE=$(find .theos/obj -name "*.dylib" -type f | head -n 1)
        echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT
        echo "dylib_file=$DYLIB_FILE" >> $GITHUB_OUTPUT
        echo "Found DEB: $DEB_FILE"
        echo "Found DYLIB: $DYLIB_FILE"
    
    - name: Upload DEB package
      if: steps.find_artifacts.outputs.deb_file != ''
      uses: actions/upload-artifact@v3
      with:
        name: QQiPadModeLogin-deb
        path: ${{ steps.find_artifacts.outputs.deb_file }}
    
    - name: Upload DYLIB library
      if: steps.find_artifacts.outputs.dylib_file != ''
      uses: actions/upload-artifact@v3
      with:
        name: QQiPadModeLogin-dylib
        path: ${{ steps.find_artifacts.outputs.dylib_file }}
    
    - name: Upload all artifacts
      uses: actions/upload-artifact@v3
      with:
        name: QQiPadModeLogin-all-artifacts
        path: |
          packages/*.deb
          .theos/obj/**/*.dylib
